export {default as authRoutes }  from './auth.routes'
export {default as userRoutes }  from './user.routes'
export {default as courseRoutes }  from './course.routes'
export {default as enrollmentRoutes }  from './enrollment.routes'
export {default as orderRoutes }  from './order.routes'
export {default as settingRoutes }  from './setting.routes'
export {default as mediaRoutes }  from './media.routes'
export {default as defaultRoutes }  from './defaultRoutes'
