export {default as Home} from './Home'
export { default as HomeHero } from './hero'
export {default as HomeEnrolledInCourses} from './enrolled-in-courses'
export {default as HomeTeachingCourses} from './teaching-courses'
export { default as HomePopularCourse } from './popular-courses'
export { default as HomeSearchedCourses } from './searched-courses'
export { default as HomeFeature } from './feature'
export { default as HomeTestimonial } from './testimonial'
export { default as HomeOurTeachers } from './teachers'
export { default as HomeNewsLetter } from './newsletter'
export { default as HomeCookie } from './Cookie' 
export { default as HomeIntroVideo } from './intro-video' 

