export {default as Home} from './Home'
export { default as HomeHero } from './hero'
export { default as HomePricing} from './Pricing'
export {default as HomeEnrolledInCourses} from './enrolled-in-courses'
export {default as HomeTeachingCourses} from './teaching-courses'
export { default as HomePopularCourses } from './popular-courses'
export { default as HomeSearchedCourses } from './searched-courses'
export { default as HomeFeatureClient } from './feature-client'
export { default as HomeFeatureSpecialist } from './feature-specialist'
export { default as HomeTestimonial } from './testimonial'
export { default as HomeOurSpecialists } from './specialists'
export { default as HomeNewsLetter } from './newsletter'
export { default as HomeCookie } from './Cookie' 
export { default as HomeIntroVideo } from './intro-video' 

